/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        zinc: {
          50: "rgb(var(--zinc-50) / <alpha-value>)",
          100: "rgb(var(--zinc-100) / <alpha-value>)",
          200: "rgb(var(--zinc-200) / <alpha-value>)",
          300: "rgb(var(--zinc-300) / <alpha-value>)",
          400: "rgb(var(--zinc-400) / <alpha-value>)",
          500: "rgb(var(--zinc-500) / <alpha-value>)",
          600: "rgb(var(--zinc-600) / <alpha-value>)",
          700: "rgb(var(--zinc-700) / <alpha-value>)",
          800: "rgb(var(--zinc-800) / <alpha-value>)",
          900: "rgb(var(--zinc-900) / <alpha-value>)",
          950: "rgb(var(--zinc-950) / <alpha-value>)",
        },
        "on-primary": "#1d00a5",
        "on-secondary-container": "#b5b8c3",
        "inverse-on-surface": "#302f39",
        "outline-variant": "#464555",
        "on-primary-fixed": "#0f0069",
        "on-secondary": "#2c3039",
        "background": "rgb(var(--background) / <alpha-value>)",
        "tertiary-fixed": "#ffdbcc",
        "surface-container-lowest": "#0e0d16",
        "secondary": "#c3c6d1",
        "primary-fixed-dim": "#c3c0ff",
        "on-secondary-fixed": "#181c24",
        "primary": "#c3c0ff",
        "secondary-fixed-dim": "#c3c6d1",
        "on-tertiary-container": "#ffd2be",
        "on-tertiary-fixed": "#351000",
        "on-error": "#690005",
        "surface-variant": "#35343e",
        "on-primary-container": "#dad7ff",
        "surface-dim": "#13121b",
        "error": "#ffb4ab",
        "tertiary": "#ffb695",
        "surface-tint": "#c3c0ff",
        "surface-bright": "#393842",
        "surface-container-high": "#2a2933",
        "surface-container-low": "#151921",
        "on-secondary-fixed-variant": "#434750",
        "inverse-surface": "#e4e1ee",
        "on-tertiary-fixed-variant": "#7b2f00",
        "surface-container": "#1f1f28",
        "primary-fixed": "#e2dfff",
        "secondary-fixed": "#dfe2ee",
        "on-surface-variant": "#c7c4d8",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#a44100",
        "tertiary-fixed-dim": "#ffb695",
        "primary-container": "#4f46e5",
        "outline": "#918fa1",
        "on-background": "#e4e1ee",
        "on-tertiary": "#571f00",
        "surface": "#13121b",
        "secondary-container": "#454952",
        "on-primary-fixed-variant": "#3323cc",
        "surface-container-highest": "#35343e",
        "inverse-primary": "#4d44e3",
        "on-surface": "#e4e1ee",
        "foreground": "rgb(var(--foreground) / <alpha-value>)",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        lg: "24px",
        sm: "8px",
        xl: "40px",
        xs: "4px",
        "panel-padding": "12px",
        md: "16px",
        gutter: "1px",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "Inter", "sans-serif"],
        mono: ["var(--font-mono)", "JetBrains Mono", "monospace"],
        "body-md": ["var(--font-sans)", "Inter", "sans-serif"],
        "headline-lg": ["var(--font-sans)", "Inter", "sans-serif"],
        "label-xs": ["var(--font-sans)", "Inter", "sans-serif"],
        "code-md": ["var(--font-mono)", "JetBrains Mono", "monospace"],
        "body-sm": ["var(--font-sans)", "Inter", "sans-serif"],
        "code-sm": ["var(--font-mono)", "JetBrains Mono", "monospace"],
        "headline-md": ["var(--font-sans)", "Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-xs": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "code-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "code-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
